"""从当前 Python 环境生成应用依赖闭包的精确锁文件。

必须在生产同构的 Linux/Python 3.11 环境运行，不能在 Windows 开发机生成。
"""

import argparse
import importlib.metadata
import platform
import sys
from pathlib import Path

from packaging.requirements import Requirement
from packaging.utils import canonicalize_name


BACKEND_DIR = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT = BACKEND_DIR / 'requirements-lock-py311-linux.txt'


def direct_requirements():
    roots = []
    for raw_line in (BACKEND_DIR / 'requirements.txt').read_text(encoding='utf-8').splitlines():
        line = raw_line.strip()
        if line and not line.startswith(('#', '-')):
            roots.append(Requirement(line).name)
    return roots


def installed_dependency_closure(root_names):
    pending = list(root_names)
    resolved = {}
    missing = []
    while pending:
        requested_name = pending.pop()
        key = canonicalize_name(requested_name)
        if key in resolved:
            continue
        try:
            distribution = importlib.metadata.distribution(requested_name)
        except importlib.metadata.PackageNotFoundError:
            missing.append(requested_name)
            continue
        project_name = distribution.metadata['Name'] or requested_name
        resolved[key] = (project_name, distribution.version)
        for requirement_text in distribution.requires or []:
            requirement = Requirement(requirement_text)
            if requirement.marker and not requirement.marker.evaluate():
                continue
            pending.append(requirement.name)
    if missing:
        raise RuntimeError(f'当前环境缺少直接/传递依赖: {sorted(set(missing))}')
    return sorted(resolved.values(), key=lambda item: canonicalize_name(item[0]))


def render_lock(packages):
    header = [
        '# Generated by backend/scripts/capture_requirements_lock.py',
        f'# Python: {platform.python_version()}',
        f'# Platform: {platform.platform()}',
        '# Regenerate on the production-compatible Linux/Python 3.11 environment.',
        '',
    ]
    return '\n'.join(header + [f'{name}=={version}' for name, version in packages]) + '\n'


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--output', type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument('--allow-non-production-platform', action='store_true')
    args = parser.parse_args()

    is_expected_platform = sys.version_info[:2] == (3, 11) and platform.system() == 'Linux'
    if not is_expected_platform and not args.allow_non_production_platform:
        parser.error('锁文件只能在 Linux/Python 3.11 生成；本机结果不可用于生产')

    packages = installed_dependency_closure(direct_requirements())
    args.output.write_text(render_lock(packages), encoding='utf-8', newline='\n')
    print(f'wrote {len(packages)} packages to {args.output}')


if __name__ == '__main__':
    main()
